const $=s=>document.querySelector(s);const defaults={vehicle:{brand:"",model:"",year:"",engine:"",power:"",fuel:"",notes:""},memories:[],history:[],webSearch:true};
let state=(()=>{try{const s=JSON.parse(localStorage.getItem("autoai-state")||"{}");return{vehicle:{...defaults.vehicle,...(s.vehicle||{})},memories:Array.isArray(s.memories)?s.memories:[],history:Array.isArray(s.history)?s.history:[],webSearch:s.webSearch!==false}}catch{return structuredClone(defaults)}})();
const save=()=>localStorage.setItem("autoai-state",JSON.stringify(state));const esc=t=>String(t).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function renderVehicle(){const v=state.vehicle;$("#vehicleTitle").textContent=[v.brand,v.model,v.year].filter(Boolean).join(" ")||"Fahrzeug einrichten";$("#vehicleSub").textContent=[v.engine,v.power].filter(Boolean).join(" · ")||"Tippen zum Bearbeiten"}
function renderMem(){const l=$("#memoryList");l.innerHTML="";if(!state.memories.length){l.innerHTML='<div style="font-size:11px;color:#626c76;padding:7px 0">Noch keine Notizen.</div>';return}state.memories.slice().reverse().forEach((m,r)=>{const i=state.memories.length-1-r,d=document.createElement("div");d.className="memory";d.innerHTML=`<span>${esc(m)}</span><button>×</button>`;d.querySelector("button").onclick=()=>{state.memories.splice(i,1);save();renderMem()};l.appendChild(d)})}
function citations(t,s){let h=esc(t);for(const x of s||[])h=h.replace(new RegExp(`\\[${x.id}\\]`,"g"),`<a href="${esc(x.url)}" target="_blank" rel="noopener">[${x.id}]</a>`);return h}
function add(role,content,sources=[]){const b=$("#messages"),d=document.createElement("div");d.className=`message ${role}`;role==="assistant"?d.innerHTML=citations(content,sources):d.textContent=content;b.appendChild(d);if(role==="assistant"&&sources.length){const q=document.createElement("div");q.className="sources";q.innerHTML='<div class="sources-title">Verwendete Recherchequellen</div>'+sources.map(s=>`<a class="source" href="${esc(s.url)}" target="_blank" rel="noopener"><strong>[${s.id}] ${esc(s.title||"Quelle")}</strong><span>${esc(s.url)}</span></a>`).join("");b.appendChild(q)}b.scrollTop=b.scrollHeight}
function renderHistory(){if(!state.history.length)return;$("#messages").innerHTML="";state.history.forEach(m=>add(m.role,m.content,m.sources||[]))}
async function ask(text){if(!text.trim())return;const h=state.history.slice(-12).map(({role,content})=>({role,content}));state.history.push({role:"user",content:text});save();add("user",text);const t=document.createElement("div");t.className="thinking";t.textContent=state.webSearch?"🔎 Suche nach passenden Quellen und prüfe den Fall …":"🔧 Analysiere den Fall …";$("#messages").appendChild(t);$("#send").disabled=true;$("#input").disabled=true;$("#status").textContent="Analysiert …";try{const r=await fetch("/api/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:text,vehicle:state.vehicle,memories:state.memories,history:h,webSearch:state.webSearch})}),d=await r.json();if(!r.ok)throw new Error(d.detail||d.error||"Fehler");t.remove();state.history.push({role:"assistant",content:d.answer,sources:d.sources||[]});save();add("assistant",d.answer,d.sources||[]);$("#status").textContent=d.searchWarning?"KI aktiv · Websuche mit Fehler":(state.webSearch?"KI + Websuche aktiv":"KI aktiv")}catch(e){t.textContent="⚠️ "+e.message;$("#status").textContent="Fehler"}finally{$("#send").disabled=false;$("#input").disabled=false;$("#input").focus()}}
$("#chatForm").onsubmit=e=>{e.preventDefault();const i=$("#input"),t=i.value.trim();if(t){i.value="";ask(t)}};document.querySelectorAll(".quick").forEach(b=>b.onclick=()=>ask(b.textContent.trim()));function openVehicle(){Object.entries(state.vehicle).forEach(([k,v])=>{const e=$("#"+k);if(e)e.value=v||""});$("#vehicleModal").classList.remove("hidden")}$("#vehicleBtn").onclick=openVehicle;$("#mobileVehicle").onclick=openVehicle;$("#saveVehicle").onclick=()=>{["brand","model","year","engine","power","fuel","notes"].forEach(k=>state.vehicle[k]=$("#"+k).value.trim());save();renderVehicle();$("#vehicleModal").classList.add("hidden")};$("#addMemoryBtn").onclick=()=>{$("#memoryInput").value="";$("#memoryModal").classList.remove("hidden")};$("#saveMemory").onclick=()=>{const v=$("#memoryInput").value.trim();if(v){state.memories.push(v.slice(0,500));save();renderMem();$("#memoryModal").classList.add("hidden")}};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.add("hidden"));$("#webSearch").checked=state.webSearch;$("#webSearch").onchange=e=>{state.webSearch=e.target.checked;save();$("#searchState").textContent=state.webSearch?"🌐 Web-/Forensuche aktiv":"🧠 Nur KI, keine Websuche"};$("#newChat").onclick=()=>{if(confirm("Aktuellen Chat löschen? Fahrzeugprofil und Diagnose-Notizen bleiben erhalten.")){state.history=[];save();location.reload()}};renderVehicle();renderMem();renderHistory();
